graph TD
  App[Cove Rails application]

  App --> Controllers[app/controllers]
  Controllers --> ApplicationController[ApplicationController]
  Controllers --> MarketingPreferencesController[MarketingPreferencesController]
  Controllers --> AccountsController[AccountsController]
  Controllers --> AccountUsersController[AccountUsersController]
  Controllers --> AccountInvitationsController[AccountInvitationsController]
  Controllers --> AccountsControllers[accounts/]
  AccountsControllers --> FamilyInvitationsController[AccountInvitationsController]
  AccountsControllers --> FamilyTransfersController[TransfersController]
  Controllers --> AccountControllers[account/]
  AccountControllers --> PasswordResetLinksController[PasswordResetLinksController]
  Controllers --> StudentsController[StudentsController]
  Controllers --> StudentControllers[students/]
  StudentControllers --> StudentArchivesController[ArchivesController]
  StudentControllers --> StudentKeptController[KeptController]
  Controllers --> DevControllers[dev/]
  Controllers --> Concerns[concerns/]
  Concerns --> PremiumAccess[PremiumAccess]
  Concerns --> PlanChangeGuard[PlanChangeGuard]
  Controllers --> BillingControllers[billing/subscriptions/]
  BillingControllers --> PlanChangesController[PlanChangesController]
  Controllers --> InboundWebhooksControllers[inbound_webhooks/]
  InboundWebhooksControllers --> LoopsWebhookController[LoopsController]

  App --> Models[app/models]
  Models --> User[User]
  Models --> Account[Account]
  Models --> Student[Student]
  Models --> Current[Current]
  Models --> UserConcerns[user/]
  UserConcerns --> AccountCreatedEmail[AccountCreatedEmail]
  UserConcerns --> MarketingConsent[MarketingConsent]
  Models --> LoopsWebhookEvent[LoopsWebhookEvent]
  Models --> PaySubscriptionConcern[pay/subscription/PlanSchedule]

  App --> Mailers[app/mailers]
  Mailers --> UserMailer[UserMailer]

  App --> Jobs[app/jobs]
  Jobs --> LoopsContactSyncJob[LoopsContactSyncJob]
  Jobs --> LoopsContactDeletionJob[LoopsContactDeletionJob]
  Jobs --> LoopsContactBackfillJob[LoopsContactBackfillJob]
  Jobs --> LoopsRetryable[concerns/loops_retryable]
  Jobs --> LoopsWebhookEventJob[LoopsWebhookEventJob]
  Jobs --> LoopsWebhookEventPruningJob[LoopsWebhookEventPruningJob]
  Jobs --> LoopsWebhookEventSweepJob[LoopsWebhookEventSweepJob]

  App --> Services[app/services]
  Services --> LoopsContactSynchronizer[LoopsContactSynchronizer]
  Services --> LoopsWebhookEventProcessor[LoopsWebhookEventProcessor]
  Services --> LoopsWebhookSignature[LoopsWebhookSignature]
  Services --> FamilyInvitationAcceptance[FamilyInvitationAcceptance]

  App --> Views[app/views]
  Views --> DeviseViews[devise/registrations]
  Views --> AccountViews[account/]
  Views --> AccountsViews[accounts/]
  Views --> AccountInvitationViews[account_invitations/]
  Views --> AccountUserViews[account_users/]
  Views --> DashboardViews[dashboard/]
  Views --> StudentViews[students/]
  StudentViews --> StudentLimitPrompt[_limit_prompt.html.erb]
  Views --> PublicViews[public/]
  Views --> UserViews[users/]
  Views --> BillingViews[billing/subscriptions/]
  BillingViews --> PlanChangeView[plan_changes/show]

  App --> Components[app/components]
  Components --> FormComponents[form and input components]
  Components --> NavigationComponents[navigation components]
  Components --> FeedbackComponents[alert, toast, modal, tooltip]

  App --> JavaScript[app/javascript]
  JavaScript --> Stimulus[controllers/]
  JavaScript --> Channels[channels/]

  App --> Configuration[config]
  Configuration --> Routes[routes.rb]
  Configuration --> LoopsConfig[loops.yml]
  Configuration --> RouteModules[routes/]
  RouteModules --> UserRoutes[users.rb]
  RouteModules --> AccountRoutes[accounts.rb]
  RouteModules --> BillingRoutes[billing.rb]
  RouteModules --> ApiRoutes[api.rb]
  RouteModules --> WebhookRoutes[webhooks.rb]
  Configuration --> RecurringYml[recurring.yml]

  App --> Database[db]
  Database --> Migrations[migrate/]
  Database --> Schema[schema.rb]

  App --> Tasks[lib/tasks]
  Tasks --> LoopsContactsTask[loops_contacts.rake]

  MarketingPreferencesController --> User
  MarketingPreferencesController --> DeviseViews
  User --> MarketingConsent
  User --> AccountCreatedEmail
  AccountCreatedEmail --> UserMailer
  MarketingConsent --> LoopsContactSyncJob
  MarketingConsent --> LoopsContactDeletionJob
  LoopsContactSyncJob --> LoopsContactSynchronizer
  LoopsContactDeletionJob --> LoopsContactSynchronizer
  LoopsContactBackfillJob --> LoopsContactSynchronizer
  LoopsContactSyncJob --> LoopsRetryable
  LoopsContactDeletionJob --> LoopsRetryable
  LoopsContactBackfillJob --> LoopsRetryable
  LoopsContactSynchronizer --> LoopsConfig
  LoopsContactsTask --> LoopsContactBackfillJob
  WebhookRoutes --> LoopsWebhookController
  LoopsWebhookController --> LoopsWebhookSignature
  LoopsWebhookController --> LoopsWebhookEvent
  LoopsWebhookController --> LoopsWebhookEventJob
  LoopsWebhookEventJob --> LoopsWebhookEventProcessor
  LoopsWebhookEventProcessor --> User
  LoopsWebhookEventProcessor --> LoopsConfig
  RecurringYml --> LoopsWebhookEventPruningJob
  RecurringYml --> LoopsWebhookEventSweepJob
  LoopsWebhookEventPruningJob --> LoopsWebhookEvent
  LoopsWebhookEventSweepJob --> LoopsWebhookEvent
  LoopsWebhookEventSweepJob --> LoopsWebhookEventJob
  PlanChangesController --> PlanChangeGuard
  PlanChangesController --> PaySubscriptionConcern
  PlanChangesController --> PlanChangeView
  StudentsController --> Student
  StudentArchivesController --> Student
  StudentKeptController --> Student
  Student --> Account
