graph TD
  App[Cove Rails application]

  App --> Controllers[app/controllers]
  Controllers --> ApplicationController[ApplicationController]
  Controllers --> MarketingPreferencesController[MarketingPreferencesController]
  Controllers --> DevControllers[dev/]
  Controllers --> Concerns[concerns/]
  Controllers --> InboundWebhooksControllers[inbound_webhooks/]
  InboundWebhooksControllers --> LoopsWebhookController[LoopsController]

  App --> Models[app/models]
  Models --> User[User]
  Models --> Account[Account]
  Models --> Current[Current]
  Models --> UserConcerns[user/]
  UserConcerns --> MarketingConsent[MarketingConsent]
  Models --> LoopsWebhookEvent[LoopsWebhookEvent]

  App --> Jobs[app/jobs]
  Jobs --> LoopsContactSyncJob[LoopsContactSyncJob]
  Jobs --> LoopsContactDeletionJob[LoopsContactDeletionJob]
  Jobs --> LoopsContactBackfillJob[LoopsContactBackfillJob]
  Jobs --> LoopsRetryable[concerns/loops_retryable]
  Jobs --> LoopsWebhookEventJob[LoopsWebhookEventJob]
  Jobs --> LoopsWebhookEventPruningJob[LoopsWebhookEventPruningJob]

  App --> Services[app/services]
  Services --> LoopsContactSynchronizer[LoopsContactSynchronizer]
  Services --> LoopsWebhookEventProcessor[LoopsWebhookEventProcessor]
  Services --> LoopsWebhookSignature[LoopsWebhookSignature]

  App --> Views[app/views]
  Views --> DeviseViews[devise/registrations]
  Views --> AccountViews[account/]
  Views --> DashboardViews[dashboard/]
  Views --> PublicViews[public/]
  Views --> UserViews[users/]

  App --> Components[app/components]
  Components --> FormComponents[form and input components]
  Components --> NavigationComponents[navigation components]
  Components --> FeedbackComponents[alert, toast, modal, tooltip]

  App --> JavaScript[app/javascript]
  JavaScript --> Stimulus[controllers/]
  JavaScript --> Channels[channels/]

  App --> Configuration[config]
  Configuration --> Routes[routes.rb]
  Configuration --> LoopsConfig[loops.yml]
  Configuration --> RouteModules[routes/]
  RouteModules --> UserRoutes[users.rb]
  RouteModules --> AccountRoutes[accounts.rb]
  RouteModules --> BillingRoutes[billing.rb]
  RouteModules --> ApiRoutes[api.rb]
  RouteModules --> WebhookRoutes[webhooks.rb]
  Configuration --> RecurringYml[recurring.yml]

  App --> Database[db]
  Database --> Migrations[migrate/]
  Database --> Schema[schema.rb]

  App --> Tasks[lib/tasks]
  Tasks --> LoopsContactsTask[loops_contacts.rake]

  MarketingPreferencesController --> User
  MarketingPreferencesController --> DeviseViews
  User --> MarketingConsent
  MarketingConsent --> LoopsContactSyncJob
  MarketingConsent --> LoopsContactDeletionJob
  LoopsContactSyncJob --> LoopsContactSynchronizer
  LoopsContactDeletionJob --> LoopsContactSynchronizer
  LoopsContactBackfillJob --> LoopsContactSynchronizer
  LoopsContactSyncJob --> LoopsRetryable
  LoopsContactDeletionJob --> LoopsRetryable
  LoopsContactBackfillJob --> LoopsRetryable
  LoopsContactSynchronizer --> LoopsConfig
  LoopsContactsTask --> LoopsContactBackfillJob
  WebhookRoutes --> LoopsWebhookController
  LoopsWebhookController --> LoopsWebhookSignature
  LoopsWebhookController --> LoopsWebhookEvent
  LoopsWebhookController --> LoopsWebhookEventJob
  LoopsWebhookEventJob --> LoopsWebhookEventProcessor
  LoopsWebhookEventProcessor --> User
  LoopsWebhookEventProcessor --> LoopsConfig
  RecurringYml --> LoopsWebhookEventPruningJob
  LoopsWebhookEventPruningJob --> LoopsWebhookEvent
