flowchart TB
  subgraph buttons["Buttons"]
    buttons_component["Buttons::Component"]
  end

  subgraph forms["Forms"]
    %% Components go here.
  end

  subgraph feedback["Feedback"]
    %% Components go here.
  end

  subgraph overlays["Overlays"]
    %% Components go here.
  end

  subgraph navigation["Navigation"]
    %% Components go here.
  end

  subgraph data_display["Data Display"]
    %% Components go here.
  end
