Jumpstart.config = Jumpstart::Configuration.new({"application_name" => "Cove",
 "business_name" => "Cove",
 "business_address" => "307 N 990 E\n" + "Salem, UT 84653",
 "domain" => "covehomeschool.com",
 "support_email" => "support@covehomeschool.com",
 "default_from_email" => "Cove <notify@covehomeschool.com>",
 "background_job_processor" => nil,
 "email_provider" => "",
 "account_types" => "personal",
 "apns" => false,
 "fcm" => false,
 "integrations" => [],
 "omniauth_providers" => ["google-oauth2"],
 "payment_processors" => ["stripe"],
 "multitenancy" => [],
 "gems" => []})
